### ISSUE TITLE
...docs/whatsapp ?

### ISSUE THREAD

**Issue by emahuni** [getninjas/whatsapp#9]
The links you provided in your readme are not working. I am not sure how this whole api is supposed to work without the actual whatsapp official api. Was it there and removed or something?

**Comment by Eliada** [comment]
Unfortunately Facebook/Whatsapp has not released the WhatsApp API to the public, as it's still in closed beta.

As soon as it is publicly released that link should work.

**Comment by emahuni** [comment]
How can I join the beta program 😊

**Comment by Eliada** [comment]
I wish I could help you, but that's up to facebook...

**Comment by Eliada** [comment]
Hi @emahuni,

Great news, the documentation for the WhatsApp Enterprize account is now public avaliable :tada::tada::tada: 
Everyone can read it here: https://developers.facebook.com/docs/whatsapp/

The steps for getting access are there too

**Comment by Eliada** [comment]
Now I just need to update teh README

**Comment by Eliada** [comment]
fixed on #12
